spring.application.name=BienestarService

server.port=8082

spring.mongodb.uri=${MONGO_URI}
spring.mongodb.database=bienestardb

# URL del events-service
events.service.url=${EVENTS_SERVICE_URL:http://localhost:8081/events}
