spring.application.name=BienestarService

server.port=8083

spring.data.mongodb.uri=mongodb+srv://andrescardozom_db_user:SMiJnH2UdxzTBq8V@cluster0.itzczli.mongodb.net/bienestardb?appName=Cluster0

# URL del events-service
events.service.url=${EVENTS_SERVICE_URL:http://localhost:8081/events}
