spring.application.name=BienestarService

server.port=8082

spring.data.mongodb.uri=mongodb+srv://CarlosAvellaneda:Alpha2026@cvds.bhasc0d.mongodb.net/?appName=CVDS

# URL del events-service
events.service.url=http://localhost:8081/events

